-- Schema base de donnees (VERSION CORRIGÉE - PKs INT GENERATED BY DEFAULT AS IDENTITY)

CREATE TABLE subscription(
   subscription_id INT GENERATED BY DEFAULT AS IDENTITY,
   subscription_name VARCHAR(50) NOT NULL,
   subscription_active BOOLEAN NOT NULL DEFAULT TRUE,
   subscription_auto_renewal BOOLEAN NOT NULL DEFAULT TRUE,
   subscription_public BOOLEAN NOT NULL DEFAULT TRUE,
   PRIMARY KEY(subscription_id),
   UNIQUE(subscription_name)
);

CREATE TABLE program(
   program_id INT GENERATED BY DEFAULT AS IDENTITY,
   program_name VARCHAR(50) NOT NULL,
   program_goal VARCHAR(50) NOT NULL CHECK(program_goal IN ('weight loss', 'muscle gain', 'toning', 'endurance', 'strength', 'flexibility', 'wellness', 'rehabilitation')),
   program_session_count INT NOT NULL CHECK(program_session_count > 0),
   program_duration_days SMALLINT NOT NULL CHECK(program_duration_days > 0),
   program_active BOOLEAN NOT NULL DEFAULT TRUE,
   PRIMARY KEY(program_id),
   UNIQUE(program_name)
);

CREATE TABLE equipment(
   equipment_id INT GENERATED BY DEFAULT AS IDENTITY,
   equipment_name VARCHAR(50) NOT NULL,
   PRIMARY KEY(equipment_id),
   UNIQUE(equipment_name)
);

CREATE TABLE meal(
   meal_id INT GENERATED BY DEFAULT AS IDENTITY,
   meal_name VARCHAR(50) NOT NULL,
   meal_description TEXT,
   meal_preparation TEXT,
   PRIMARY KEY(meal_id),
   UNIQUE(meal_name)
);

CREATE TABLE food(
   food_id INT GENERATED BY DEFAULT AS IDENTITY,
   food_name VARCHAR(50) NOT NULL,
   food_allergens VARCHAR(255),
   food_calories_per_100g SMALLINT NOT NULL CHECK(food_calories_per_100g >= 0),
   food_protein_per_100g DECIMAL(5,2) NOT NULL CHECK(food_protein_per_100g >= 0),
   food_fiber_per_100g DECIMAL(5,2) NOT NULL CHECK(food_fiber_per_100g >= 0),
   food_sugar_per_100g DECIMAL(5,2) NOT NULL CHECK(food_sugar_per_100g >= 0),
   food_carbs_per_100g DECIMAL(5,2) NOT NULL CHECK(food_carbs_per_100g >= 0),
   food_salt_per_100g DECIMAL(5,2) NOT NULL CHECK(food_salt_per_100g >= 0),
   food_fat_per_100g DECIMAL(5,2) NOT NULL CHECK(food_fat_per_100g >= 0),
   food_saturated_fat_per_100g DECIMAL(5,2) NOT NULL CHECK(food_saturated_fat_per_100g >= 0),
   PRIMARY KEY(food_id),
   UNIQUE(food_name)
);

CREATE TABLE company(
   company_id INT GENERATED BY DEFAULT AS IDENTITY,
   company_name VARCHAR(50) NOT NULL,
   company_email VARCHAR(100) NOT NULL,
   company_partnership_date DATE NOT NULL,
   company_type VARCHAR(50) NOT NULL CHECK(company_type IN ('SME', 'mid-size', 'large enterprise', 'startup', 'association', 'public sector')),
   PRIMARY KEY(company_id),
   UNIQUE(company_email),
   UNIQUE(company_name)
);

CREATE TABLE subscription_pricing(
   pricing_id INT GENERATED BY DEFAULT AS IDENTITY,
   pricing_name VARCHAR(50) NOT NULL,
   pricing_amount DECIMAL(5,2) NOT NULL CHECK(pricing_amount >= 0),
   pricing_start_date DATE NOT NULL,
   pricing_end_date DATE,
   PRIMARY KEY(pricing_id),
   UNIQUE(pricing_name),
   CHECK(pricing_end_date IS NULL OR pricing_end_date > pricing_start_date)
);

CREATE TABLE session(
   session_id INT GENERATED BY DEFAULT AS IDENTITY,
   session_order INT NOT NULL,
   program_id INT NOT NULL,
   PRIMARY KEY(session_id),
   UNIQUE(program_id, session_order),
   FOREIGN KEY(program_id) REFERENCES program(program_id)
);

CREATE TABLE nutritionist(
   nutritionist_id INT GENERATED BY DEFAULT AS IDENTITY,
   nutritionist_lastname VARCHAR(50) NOT NULL,
   nutritionist_firstname VARCHAR(50) NOT NULL,
   nutritionist_email VARCHAR(100) NOT NULL,
   nutritionist_phone VARCHAR(50) NOT NULL,
   nutritionist_gender VARCHAR(20) NOT NULL CHECK(nutritionist_gender IN ('Male', 'Female', 'Other')),
   PRIMARY KEY(nutritionist_id),
   UNIQUE(nutritionist_email),
   UNIQUE(nutritionist_phone)
);

CREATE TABLE "user"(
   user_id INT GENERATED BY DEFAULT AS IDENTITY,
   user_role VARCHAR(50) NOT NULL DEFAULT 'user' CHECK(user_role IN ('admin', 'user')),
   user_password VARCHAR(255) NOT NULL,
   user_email VARCHAR(100) NOT NULL,
   user_lastname VARCHAR(50) NOT NULL,
   user_firstname VARCHAR(50) NOT NULL,
   user_birthdate DATE NOT NULL,
   user_country VARCHAR(50) NOT NULL,
   user_city VARCHAR(50) NOT NULL,
   user_gender VARCHAR(20) NOT NULL CHECK(user_gender IN ('Male', 'Female', 'Other')),
   user_phone VARCHAR(50),
   user_height DECIMAL(5,2) NOT NULL CHECK(user_height > 0),
   user_weight DECIMAL(5,2) CHECK(user_weight > 0),
   company_id INT,
   PRIMARY KEY(user_id),
   UNIQUE(user_email),
   UNIQUE(user_phone),
   FOREIGN KEY(company_id) REFERENCES company(company_id)
);

CREATE TABLE consultation(
   consultation_id INT GENERATED BY DEFAULT AS IDENTITY,
   consultation_video_link VARCHAR(255),
   consultation_report TEXT,
   consultation_datetime TIMESTAMP NOT NULL,
   user_id INT NOT NULL,
   nutritionist_id INT NOT NULL,
   PRIMARY KEY(consultation_id),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id),
   FOREIGN KEY(nutritionist_id) REFERENCES nutritionist(nutritionist_id)
);

CREATE TABLE exercise(
   exercise_id INT GENERATED BY DEFAULT AS IDENTITY,
   exercise_name VARCHAR(50) NOT NULL,
   exercise_type VARCHAR(100) NOT NULL CHECK(exercise_type IN ('cardio', 'strength training', 'stretching', 'yoga', 'hiit', 'pilates', 'crossfit', 'swimming')),
   exercise_difficulty VARCHAR(50) NOT NULL CHECK(exercise_difficulty IN ('beginner', 'intermediate', 'advanced', 'expert')),
   exercise_duration_minutes SMALLINT NOT NULL CHECK(exercise_duration_minutes > 0),
   exercise_calories_burned SMALLINT NOT NULL CHECK(exercise_calories_burned >= 0),
   exercise_target_muscles VARCHAR(255) NOT NULL,
   exercise_demo_link VARCHAR(255),
   exercise_instructions TEXT NOT NULL,
   equipment_id INT,
   PRIMARY KEY(exercise_id),
   UNIQUE(exercise_name),
   FOREIGN KEY(equipment_id) REFERENCES equipment(equipment_id)
);

CREATE TABLE user_tracking(
   tracking_id INT GENERATED BY DEFAULT AS IDENTITY,
   tracking_date DATE NOT NULL,
   tracking_weight DECIMAL(5,2) CHECK(tracking_weight > 0),
   tracking_sleep_hours SMALLINT CHECK(tracking_sleep_hours BETWEEN 0 AND 24),
   tracking_avg_heart_rate SMALLINT CHECK(tracking_avg_heart_rate > 0),
   tracking_steps_count INT CHECK(tracking_steps_count >= 0),
   user_id INT NOT NULL,
   PRIMARY KEY(tracking_id),
   UNIQUE(user_id, tracking_date),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id)
);

CREATE TABLE user_invoice(
   invoice_id INT GENERATED BY DEFAULT AS IDENTITY,
   invoice_date DATE NOT NULL,
   invoice_amount DECIMAL(10,2) NOT NULL CHECK(invoice_amount >= 0),
   user_id INT NOT NULL,
   subscription_id INT NOT NULL,
   PRIMARY KEY(invoice_id),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id),
   FOREIGN KEY(subscription_id) REFERENCES subscription(subscription_id)
);

CREATE TABLE exercise_session(
   exercise_session_id INT GENERATED BY DEFAULT AS IDENTITY,
   exercise_session_start TIMESTAMP NOT NULL,
   exercise_session_end TIMESTAMP,
   user_id INT NOT NULL,
   session_id INT NOT NULL,
   exercise_id INT NOT NULL,
   PRIMARY KEY(exercise_session_id),
   CHECK(exercise_session_end IS NULL OR exercise_session_end > exercise_session_start),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id),
   FOREIGN KEY(session_id) REFERENCES session(session_id),
   FOREIGN KEY(exercise_id) REFERENCES exercise(exercise_id)
);

CREATE TABLE user_subscription(
   subscription_id INT,
   user_id INT,
   subscription_start_date DATE NOT NULL,
   subscription_end_date DATE,
   PRIMARY KEY(subscription_id, user_id),
   CHECK(subscription_end_date IS NULL OR subscription_end_date > subscription_start_date),
   FOREIGN KEY(subscription_id) REFERENCES subscription(subscription_id),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id)
);

CREATE TABLE follows_program(
   user_id INT,
   program_id INT,
   program_enrollment_date DATE NOT NULL,
   PRIMARY KEY(user_id, program_id),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id),
   FOREIGN KEY(program_id) REFERENCES program(program_id)
);

CREATE TABLE includes_meal(
   program_id INT,
   meal_id INT,
   PRIMARY KEY(program_id, meal_id),
   FOREIGN KEY(program_id) REFERENCES program(program_id),
   FOREIGN KEY(meal_id) REFERENCES meal(meal_id)
);

CREATE TABLE composed_of(
   meal_id INT,
   food_id INT,
   quantity_grams DECIMAL(10,2) NOT NULL CHECK(quantity_grams > 0),
   PRIMARY KEY(meal_id, food_id),
   FOREIGN KEY(meal_id) REFERENCES meal(meal_id),
   FOREIGN KEY(food_id) REFERENCES food(food_id)
);

CREATE TABLE company_subscription(
   subscription_id INT,
   company_id INT,
   subscription_start_date DATE NOT NULL,
   subscription_end_date DATE,
   PRIMARY KEY(subscription_id, company_id),
   CHECK(subscription_end_date IS NULL OR subscription_end_date > subscription_start_date),
   FOREIGN KEY(subscription_id) REFERENCES subscription(subscription_id),
   FOREIGN KEY(company_id) REFERENCES company(company_id)
);

CREATE TABLE subscription_price(
   subscription_id INT,
   pricing_id INT,
   PRIMARY KEY(subscription_id, pricing_id),
   FOREIGN KEY(subscription_id) REFERENCES subscription(subscription_id),
   FOREIGN KEY(pricing_id) REFERENCES subscription_pricing(pricing_id)
);

CREATE TABLE session_exercise(
   exercise_id INT,
   session_id INT,
   exercise_order INT NOT NULL CHECK(exercise_order > 0),
   PRIMARY KEY(exercise_id, session_id),
   UNIQUE(session_id, exercise_order),
   FOREIGN KEY(exercise_id) REFERENCES exercise(exercise_id),
   FOREIGN KEY(session_id) REFERENCES session(session_id)
);


-- ============================================================
-- INSERTION DES DONNÉES
-- Les IDs sont auto-générés dans l'ordre d'insertion :
--   subscription     : Basic Plan=1, Pro Plan=2, Corporate Plan=3
--   program          : Weight Loss Starter=1, Muscle Builder=2, Yoga Flex=3
--   equipment        : Dumbbell=1, Treadmill=2, Yoga Mat=3
--   meal             : Chicken Salad=1, Protein Shake=2
--   food             : Chicken Breast=1, Lettuce=2, Milk=3
--   company          : FitCorp=1, WellnessInc=2
--   subscription_pricing : Basic Monthly=1, Pro Monthly=2
--   session          : sess1=1, sess2=2
--   nutritionist     : Sophie Dupont=1, Jean Martin=2
--   user             : Alice=1, Bob=2
--   consultation     : cons1=1
--   exercise         : Jumping Jacks=1, Dumbbell Curl=2
--   user_tracking    : track1=1
--   user_invoice     : inv1=1
--   exercise_session : exsess1=1
-- ============================================================

INSERT INTO subscription (subscription_name, subscription_active, subscription_auto_renewal, subscription_public)
VALUES
('Basic Plan', TRUE, TRUE, TRUE),
('Pro Plan', TRUE, FALSE, TRUE),
('Corporate Plan', TRUE, TRUE, FALSE);

INSERT INTO program (program_name, program_goal, program_session_count, program_duration_days, program_active)
VALUES
('Weight Loss Starter', 'weight loss', 10, 30, TRUE),
('Muscle Builder', 'muscle gain', 15, 45, TRUE),
('Yoga Flex', 'flexibility', 8, 28, TRUE);

INSERT INTO equipment (equipment_name)
VALUES
('Dumbbell'),
('Treadmill'),
('Yoga Mat');

INSERT INTO meal (meal_name, meal_description, meal_preparation)
VALUES
('Chicken Salad', 'Fresh chicken with greens', 'Mix chicken with lettuce and dressing'),
('Protein Shake', 'High protein shake', 'Blend protein powder with milk and banana');

INSERT INTO food (food_name, food_allergens, food_calories_per_100g, food_protein_per_100g, food_fiber_per_100g, food_sugar_per_100g, food_carbs_per_100g, food_salt_per_100g, food_fat_per_100g, food_saturated_fat_per_100g)
VALUES
('Chicken Breast', NULL, 165, 31.0, 0.0, 0.0, 0.0, 0.1, 3.6, 1.0),
('Lettuce', NULL, 15, 1.4, 1.3, 0.8, 2.9, 0.0, 0.2, 0.0),
('Milk', 'Lactose', 42, 3.4, 0.0, 5.0, 5.0, 0.1, 1.0, 0.6);

-- FitCorp = 1, WellnessInc = 2
INSERT INTO company (company_name, company_email, company_partnership_date, company_type)
VALUES
('FitCorp', 'contact@fitcorp.com', '2024-01-15', 'mid-size'),
('WellnessInc', 'info@wellnessinc.org', '2023-11-20', 'startup');

INSERT INTO subscription_pricing (pricing_name, pricing_amount, pricing_start_date, pricing_end_date)
VALUES
('Basic Monthly', 9.99, '2024-01-01', NULL),
('Pro Monthly', 19.99, '2024-01-01', NULL);

-- program_id 1 = Weight Loss Starter
INSERT INTO session (session_order, program_id)
VALUES
(1, 1),
(2, 1);

INSERT INTO nutritionist (nutritionist_lastname, nutritionist_firstname, nutritionist_email, nutritionist_phone, nutritionist_gender)
VALUES
('Dupont', 'Sophie', 'sophie.dupont@example.com', '0600000001', 'Female'),
('Martin', 'Jean', 'jean.martin@example.com', '0600000002', 'Male');

-- Alice = user 1, Bob = user 2 (company_id 1 = FitCorp)
INSERT INTO "user" (user_role, user_password, user_email, user_lastname, user_firstname, user_birthdate, user_country, user_city, user_gender, user_phone, user_height, user_weight, company_id)
VALUES
('user', 'hashed_password_1', 'alice@example.com', 'Durand', 'Alice', '1990-05-10', 'France', 'Paris', 'Female', '0600111222', 165.0, 60.0, NULL),
('admin', 'hashed_password_2', 'bob@example.com', 'Lemoine', 'Bob', '1985-07-20', 'France', 'Lyon', 'Male', '0600222333', 180.0, 75.0, 1);

-- user_id 1 = Alice, nutritionist_id 1 = Sophie Dupont
INSERT INTO consultation (consultation_video_link, consultation_report, consultation_datetime, user_id, nutritionist_id)
VALUES
('https://zoom.us/meeting123', 'Patient shows good progress', '2026-01-15 10:00:00', 1, 1);

-- equipment_id 1 = Dumbbell
INSERT INTO exercise (exercise_name, exercise_type, exercise_difficulty, exercise_duration_minutes, exercise_calories_burned, exercise_target_muscles, exercise_demo_link, exercise_instructions, equipment_id)
VALUES
('Jumping Jacks', 'cardio', 'beginner', 10, 100, 'full body', 'https://example.com/jumping_jacks', 'Jump with legs apart and arms overhead', NULL),
('Dumbbell Curl', 'strength training', 'intermediate', 15, 150, 'biceps', 'https://example.com/dumbbell_curl', 'Curl dumbbell slowly', 1);

-- user_id 1 = Alice
INSERT INTO user_tracking (tracking_date, tracking_weight, tracking_sleep_hours, tracking_avg_heart_rate, tracking_steps_count, user_id)
VALUES
('2026-01-01', 60.0, 7, 70, 8000, 1);

-- user_id 1 = Alice, subscription_id 1 = Basic Plan
INSERT INTO user_invoice (invoice_date, invoice_amount, user_id, subscription_id)
VALUES
('2026-01-01', 9.99, 1, 1);

-- user_id 1 = Alice, session_id 1, exercise_id 1 = Jumping Jacks
INSERT INTO exercise_session (exercise_session_start, exercise_session_end, user_id, session_id, exercise_id)
VALUES
('2026-01-10 08:00:00', '2026-01-10 08:30:00', 1, 1, 1);

-- subscription_id 1 = Basic Plan, user_id 1 = Alice
INSERT INTO user_subscription (subscription_id, user_id, subscription_start_date, subscription_end_date)
VALUES
(1, 1, '2026-01-01', NULL);

-- user_id 1 = Alice, program_id 1 = Weight Loss Starter
INSERT INTO follows_program (user_id, program_id, program_enrollment_date)
VALUES
(1, 1, '2026-01-01');

-- program_id 1 = Weight Loss Starter, meal_id 1 = Chicken Salad
INSERT INTO includes_meal (program_id, meal_id)
VALUES
(1, 1);

-- meal_id 1 = Chicken Salad, food_id 1 = Chicken Breast, food_id 2 = Lettuce
INSERT INTO composed_of (meal_id, food_id, quantity_grams)
VALUES
(1, 1, 150.00),
(1, 2, 50.00);

-- subscription_id 3 = Corporate Plan, company_id 1 = FitCorp
INSERT INTO company_subscription (subscription_id, company_id, subscription_start_date, subscription_end_date)
VALUES
(3, 1, '2025-12-01', NULL);

-- subscription_id 1 = Basic Plan / pricing_id 1, subscription_id 2 = Pro Plan / pricing_id 2
INSERT INTO subscription_price (subscription_id, pricing_id)
VALUES
(1, 1),
(2, 2);

-- exercise_id 1 = Jumping Jacks / session_id 1, exercise_id 2 = Dumbbell Curl / session_id 2
INSERT INTO session_exercise (exercise_id, session_id, exercise_order)
VALUES
(1, 1, 1),
(2, 2, 1);