CREATE TABLE subscription(
   subscription_id VARCHAR(50),
   subscription_name VARCHAR(50) NOT NULL,
   subscription_active BOOLEAN NOT NULL DEFAULT TRUE,
   subscription_auto_renewal BOOLEAN NOT NULL DEFAULT TRUE,
   subscription_public BOOLEAN NOT NULL DEFAULT TRUE, -- To differentiate from company subscriptions
   PRIMARY KEY(subscription_id),
   UNIQUE(subscription_name)
);

CREATE TABLE program(
   program_id VARCHAR(50),
   program_name VARCHAR(50) NOT NULL,
   program_goal VARCHAR(50) NOT NULL CHECK(program_goal IN ('weight loss', 'muscle gain', 'toning', 'endurance', 'strength', 'flexibility', 'wellness', 'rehabilitation')),
   program_session_count INT NOT NULL CHECK(program_session_count > 0),
   program_duration_days SMALLINT NOT NULL CHECK(program_duration_days > 0),
   program_active BOOLEAN NOT NULL DEFAULT TRUE,
   PRIMARY KEY(program_id),
   UNIQUE(program_name)
);

CREATE TABLE equipment(
   equipment_id VARCHAR(50),
   equipment_name VARCHAR(50) NOT NULL,
   PRIMARY KEY(equipment_id),
   UNIQUE(equipment_name)
);

CREATE TABLE meal(
   meal_id VARCHAR(50),
   meal_name VARCHAR(50) NOT NULL,
   meal_description TEXT,
   meal_preparation TEXT,
   PRIMARY KEY(meal_id),
   UNIQUE(meal_name)
);

CREATE TABLE food(
   food_id VARCHAR(50),
   food_name VARCHAR(50) NOT NULL,
   food_allergens VARCHAR(255),
   food_calories_per_100g SMALLINT NOT NULL CHECK(food_calories_per_100g >= 0),
   food_protein_per_100g DECIMAL(5,2) NOT NULL CHECK(food_protein_per_100g >= 0),
   food_fiber_per_100g DECIMAL(5,2) NOT NULL CHECK(food_fiber_per_100g >= 0),
   food_sugar_per_100g DECIMAL(5,2) NOT NULL CHECK(food_sugar_per_100g >= 0),
   food_carbs_per_100g DECIMAL(5,2) NOT NULL CHECK(food_carbs_per_100g >= 0),
   food_salt_per_100g DECIMAL(5,2) NOT NULL CHECK(food_salt_per_100g >= 0),
   food_fat_per_100g DECIMAL(5,2) NOT NULL CHECK(food_fat_per_100g >= 0),
   food_saturated_fat_per_100g DECIMAL(5,2) NOT NULL CHECK(food_saturated_fat_per_100g >= 0),
   PRIMARY KEY(food_id),
   UNIQUE(food_name)
);

CREATE TABLE company(
   company_id INT GENERATED BY DEFAULT AS IDENTITY,
   company_name VARCHAR(50) NOT NULL,
   company_email VARCHAR(100) NOT NULL,
   company_partnership_date DATE NOT NULL,
   company_type VARCHAR(50) NOT NULL CHECK(company_type IN ('SME', 'mid-size', 'large enterprise', 'startup', 'association', 'public sector')),
   PRIMARY KEY(company_id),
   UNIQUE(company_email),
   UNIQUE(company_name)
);

CREATE TABLE subscription_pricing(
   pricing_id VARCHAR(50),
   pricing_name VARCHAR(50) NOT NULL,
   pricing_amount DECIMAL(5,2) NOT NULL CHECK(pricing_amount >= 0),
   pricing_start_date DATE NOT NULL,
   pricing_end_date DATE,
   PRIMARY KEY(pricing_id),
   UNIQUE(pricing_name),
   CHECK(pricing_end_date IS NULL OR pricing_end_date > pricing_start_date)
);

CREATE TABLE session(
   session_id VARCHAR(50),
   session_order INT NOT NULL,
   program_id VARCHAR(50) NOT NULL,
   PRIMARY KEY(session_id),
   UNIQUE(program_id, session_order),
   FOREIGN KEY(program_id) REFERENCES program(program_id)
);

CREATE TABLE nutritionist(
   nutritionist_id VARCHAR(50),
   nutritionist_lastname VARCHAR(50) NOT NULL,
   nutritionist_firstname VARCHAR(50) NOT NULL,
   nutritionist_email VARCHAR(100) NOT NULL,
   nutritionist_phone VARCHAR(50) NOT NULL,
   nutritionist_gender VARCHAR(20) NOT NULL CHECK(nutritionist_gender IN ('Male', 'Female', 'Other')),
   PRIMARY KEY(nutritionist_id),
   UNIQUE(nutritionist_email),
   UNIQUE(nutritionist_phone)
);

CREATE TABLE "user"(
   user_id VARCHAR(50) NOT NULL,
   user_role VARCHAR(50) NOT NULL DEFAULT 'user' CHECK(user_role IN ('admin', 'user')),
   user_password VARCHAR(255) NOT NULL,
   user_email VARCHAR(100) NOT NULL,
   user_lastname VARCHAR(50) NOT NULL,
   user_firstname VARCHAR(50) NOT NULL,
   user_birthdate DATE NOT NULL,
   user_country VARCHAR(50) NOT NULL,
   user_city VARCHAR(50) NOT NULL,
   user_gender VARCHAR(20) NOT NULL CHECK(user_gender IN ('Male', 'Female', 'Other')),
   user_phone VARCHAR(50),
   user_height DECIMAL(5,2) NOT NULL CHECK(user_height > 0),
   user_weight DECIMAL(5,2) CHECK(user_weight > 0),
   company_id INT,
   PRIMARY KEY(user_id),
   UNIQUE(user_email),
   UNIQUE(user_phone),
   FOREIGN KEY(company_id) REFERENCES company(company_id)
);

CREATE TABLE consultation(
   consultation_id VARCHAR(50),
   consultation_video_link VARCHAR(255),
   consultation_report TEXT,
   consultation_datetime TIMESTAMP NOT NULL,
   user_id VARCHAR(50) NOT NULL,
   nutritionist_id VARCHAR(50) NOT NULL,
   PRIMARY KEY(consultation_id),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id),
   FOREIGN KEY(nutritionist_id) REFERENCES nutritionist(nutritionist_id)
);

CREATE TABLE exercise(
   exercise_id VARCHAR(50),
   exercise_name VARCHAR(50) NOT NULL,
   exercise_type VARCHAR(100) NOT NULL CHECK(exercise_type IN ('cardio', 'strength training', 'stretching', 'yoga', 'hiit', 'pilates', 'crossfit', 'swimming')),
   exercise_difficulty VARCHAR(50) NOT NULL CHECK(exercise_difficulty IN ('beginner', 'intermediate', 'advanced', 'expert')),
   exercise_duration_minutes SMALLINT NOT NULL CHECK(exercise_duration_minutes > 0),
   exercise_calories_burned SMALLINT NOT NULL CHECK(exercise_calories_burned >= 0),
   exercise_target_muscles VARCHAR(255) NOT NULL,
   exercise_demo_link VARCHAR(255),
   exercise_instructions TEXT NOT NULL,
   equipment_id VARCHAR(50),
   PRIMARY KEY(exercise_id),
   UNIQUE(exercise_name),
   FOREIGN KEY(equipment_id) REFERENCES equipment(equipment_id)
);

CREATE TABLE user_tracking(
   tracking_id VARCHAR(50),
   tracking_date DATE NOT NULL,
   tracking_weight DECIMAL(5,2) CHECK(tracking_weight > 0),
   tracking_sleep_hours SMALLINT CHECK(tracking_sleep_hours BETWEEN 0 AND 24),
   tracking_avg_heart_rate SMALLINT CHECK(tracking_avg_heart_rate > 0),
   tracking_steps_count INT CHECK(tracking_steps_count >= 0),
   user_id VARCHAR(50) NOT NULL,
   PRIMARY KEY(tracking_id),
   UNIQUE(user_id, tracking_date),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id)
);

CREATE TABLE user_invoice(
   invoice_id VARCHAR(255),
   invoice_date DATE NOT NULL,
   invoice_amount DECIMAL(10,2) NOT NULL CHECK(invoice_amount >= 0),
   user_id VARCHAR(50) NOT NULL,
   subscription_id VARCHAR(50) NOT NULL,
   PRIMARY KEY(invoice_id),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id),
   FOREIGN KEY(subscription_id) REFERENCES subscription(subscription_id)
);

CREATE TABLE exercise_session(
   exercise_session_id VARCHAR(50),
   exercise_session_start TIMESTAMP NOT NULL,
   exercise_session_end TIMESTAMP,
   user_id VARCHAR(50) NOT NULL,
   session_id VARCHAR(50) NOT NULL,
   exercise_id VARCHAR(50) NOT NULL,
   PRIMARY KEY(exercise_session_id),
   CHECK(exercise_session_end IS NULL OR exercise_session_end > exercise_session_start),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id),
   FOREIGN KEY(session_id) REFERENCES session(session_id),
   FOREIGN KEY(exercise_id) REFERENCES exercise(exercise_id)
);

CREATE TABLE user_subscription(
   subscription_id VARCHAR(50),
   user_id VARCHAR(50),
   subscription_start_date DATE NOT NULL,
   subscription_end_date DATE,
   PRIMARY KEY(subscription_id, user_id),
   CHECK(subscription_end_date IS NULL OR subscription_end_date > subscription_start_date),
   FOREIGN KEY(subscription_id) REFERENCES subscription(subscription_id),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id)
);

CREATE TABLE follows_program(
   user_id VARCHAR(50),
   program_id VARCHAR(50),
   program_enrollment_date DATE NOT NULL,
   PRIMARY KEY(user_id, program_id),
   FOREIGN KEY(user_id) REFERENCES "user"(user_id),
   FOREIGN KEY(program_id) REFERENCES program(program_id)
);

CREATE TABLE includes_meal(
   program_id VARCHAR(50),
   meal_id VARCHAR(50),
   PRIMARY KEY(program_id, meal_id),
   FOREIGN KEY(program_id) REFERENCES program(program_id),
   FOREIGN KEY(meal_id) REFERENCES meal(meal_id)
);

CREATE TABLE composed_of(
   meal_id VARCHAR(50),
   food_id VARCHAR(50),
   quantity_grams DECIMAL(10,2) NOT NULL CHECK(quantity_grams > 0),
   PRIMARY KEY(meal_id, food_id),
   FOREIGN KEY(meal_id) REFERENCES meal(meal_id),
   FOREIGN KEY(food_id) REFERENCES food(food_id)
);

CREATE TABLE company_subscription(
   subscription_id VARCHAR(50),
   company_id INT,
   subscription_start_date DATE NOT NULL,
   subscription_end_date DATE,
   PRIMARY KEY(subscription_id, company_id),
   CHECK(subscription_end_date IS NULL OR subscription_end_date > subscription_start_date),
   FOREIGN KEY(subscription_id) REFERENCES subscription(subscription_id),
   FOREIGN KEY(company_id) REFERENCES company(company_id)
);

CREATE TABLE subscription_price(
   subscription_id VARCHAR(50),
   pricing_id VARCHAR(50),
   PRIMARY KEY(subscription_id, pricing_id),
   FOREIGN KEY(subscription_id) REFERENCES subscription(subscription_id),
   FOREIGN KEY(pricing_id) REFERENCES subscription_pricing(pricing_id)
);

CREATE TABLE session_exercise(
   exercise_id VARCHAR(50),
   session_id VARCHAR(50),
   exercise_order INT NOT NULL CHECK(exercise_order > 0),
   PRIMARY KEY(exercise_id, session_id),
   UNIQUE(session_id, exercise_order),
   FOREIGN KEY(exercise_id) REFERENCES exercise(exercise_id),
   FOREIGN KEY(session_id) REFERENCES session(session_id)
);